import pandas as pd
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import accuracy_score

# -----------------------------------------------------------------------------
# 1. CREATE DATASET (Historical Training Data)
# -----------------------------------------------------------------------------
data = {
    'Study_Hours': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 3, 7],
    'Sleep_Hours': [5, 4, 6, 5, 7, 8, 6, 7, 8, 9, 8, 7, 5, 6, 4, 8],
    'Passed':      [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1]  # Target (0 = Fail, 1 = Pass)
}

df = pd.DataFrame(data)

X = df[['Study_Hours', 'Sleep_Hours']]
y = df['Passed']

# -----------------------------------------------------------------------------
# 2. INSTANTIATE & TRAIN DECISION TREE MODEL
# -----------------------------------------------------------------------------
# max_depth=3 limits tree depth to prevent overfitting
# Note: Feature scaling (StandardScaler) is NOT required for Decision Trees!
dt_model = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=42)
dt_model.fit(X, y)

print("--- Decision Tree Model Trained Successfully ---")

# -----------------------------------------------------------------------------
# 3. PRINT LEARNED DECISION RULES (FLOWCHART LOGIC)
# -----------------------------------------------------------------------------
# Displays the exact IF-THEN rules generated by the tree splits
tree_rules = export_text(dt_model, feature_names=list(X.columns))
print("\nLearned Tree Structure:")
print(tree_rules)

# -----------------------------------------------------------------------------
# 4. INTERACTIVE USER INPUT FOR PREDICTION
# -----------------------------------------------------------------------------
try:
    user_study = float(input("Enter hours studied: "))
    user_sleep = float(input("Enter hours slept: "))

    # Pass input directly as DataFrame (no scaling needed)
    user_data = pd.DataFrame([[user_study, user_sleep]], columns=['Study_Hours', 'Sleep_Hours'])

    # Predict class (0 or 1) and confidence probability
    prediction = dt_model.predict(user_data)[0]
    probability = dt_model.predict_proba(user_data)[0][1] * 100

    status = "PASS" if prediction == 1 else "FAIL"
    print(f"\nPrediction: {status}")
    print(f"Confidence (Pass Probability): {probability:.1f}%")

except ValueError:
    print("Invalid input. Please enter numerical values.")